- id: "1580657732440"
  alias: "Turn on floor color light"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_1_single"
  action:
    - data:
        brightness: 255
        kelvin: 5000
        entity_id: light.32ebdcdd_color_bulb
      service: light.turn_on
- id: "1580657732441"
  alias: "Turn on floor color dark"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_1_double"
  action:
    - data:
        brightness: 127
        kelvin: 4000
        entity_id: light.32ebdcdd_color_bulb
      service: light.turn_on
- id: "1580657732442"
  alias: "Turn off floor color"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_1_hold"
  action:
    - data:
        entity_id: light.32ebdcdd_color_bulb
      service: light.turn_off
- id: "1580657732430"
  alias: "Turn on dev color green"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_2_single"
  action:
    - data:
        brightness: 255
        rgb_color:
          - 71
          - 255
          - 117
        entity_id: light.0xd74d40c9abfc8a14
      service: light.turn_on
- id: "1580657732431"
  alias: "Turn on dev color light"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_2_double"
  action:
    - data:
        brightness: 255
        kelvin: 4000
        entity_id: light.0xd74d40c9abfc8a14
      service: light.turn_on
- id: "1580657732432"
  alias: "Turn off dev color"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_2_hold"
  action:
    - data:
        entity_id: light.0xd74d40c9abfc8a14
      service: light.turn_off
- id: "1580657732420"
  alias: "Turn on all color"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_3_single"
  action:
    - data:
        entity_id: light.lv_color_all
      service: light.turn_on
- id: "1580657732422"
  alias: "Turn off all color"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_3_hold"
  action:
    - data:
        entity_id: light.lv_color_all
      service: light.turn_off
- id: "1580657732450"
  alias: Turn on aqara light when motion is detected
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: light.aqara_hub_fed8
      state: "off"
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.0x00158d0003f36469_illuminance
          below: 25
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
  action:
    - data:
        brightness: 255
        entity_id: light.aqara_hub_fed8
        rgb_color:
          - 255
          - 255
          - 255
      service: light.turn_on
- id: "1580659530371"
  alias: Turn off aqara light when motion is clear
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      for: 00:05:00
      platform: state
      to: "off"
  condition:
    - condition: state
      entity_id: light.aqara_hub_fed8
      state: "on"
  action:
    - data:
        entity_id: light.aqara_hub_fed8
      service: light.turn_off
- id: "1580657732451"
  alias: Turn on gledopto light when motion is detected
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d00044b1132_occupancy
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: light.0x00124b002113a5b2_light_cct
      state: "off"
    - condition: state
      entity_id: binary_sensor.c7b6ed93_automation_light
      state: "off"
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.0x00158d00044b1132_illuminance
          below: 25
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
  action:
    - data:
        brightness: 30
        entity_id: light.0x00124b002113a5b2_light_cct
        kelvin: 3500
      service: light.turn_on
    - data:
        payload: active
        qos: 0
        retain: true
        topic: hass/automation/light/c7b6ed93
      service: mqtt.publish
- id: "1580659530372"
  alias: Turn off gledopto light when motion is clear
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d00044b1132_occupancy
      for: 00:05:00
      platform: state
      to: "off"
  condition:
    - condition: state
      entity_id: binary_sensor.c7b6ed93_automation_light
      state: "on"
  action:
    - data:
        entity_id: light.0x00124b002113a5b2_light_cct
      service: light.turn_off
    - data:
        payload: inactive
        qos: 0
        retain: true
        topic: hass/automation/light/c7b6ed93
      service: mqtt.publish
- id: "1580662281241"
  alias: "Alarm trigger"
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      platform: state
      to: "on"
    - entity_id: binary_sensor.0x00158d00044b1132_occupancy
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.f36e737f
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.f36e737f
- id: "1580662281252"
  alias: "Process pending alarm"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "pending"
  action:
    - service: notify.heart_security_tg
      data:
        message: "The alarm pending"
        title: "Pending!"
- id: "1580662281251"
  alias: "Process triggered alarm"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "triggered"
  action:
    - service: notify.heart_security_tg
      data:
        message: "The alarm has been triggered"
        title: "Alarm!"
    - service: mqtt.publish
      data:
        payload: '{"warning":{"duration":120,"mode":"emergency","strobe":true}}'
        qos: 0
        retain: true
        topic: zigbee/0x000d6f0014f82b49/set
- id: "1580662281253"
  alias: "Process disarmed alarm"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      from: "triggered"
      to: "disarmed"
  action:
    - service: notify.heart_security_tg
      data:
        message: "The alarm has been disarmed after triggered"
        title: "Disarmed!"
    - service: mqtt.publish
      data:
        payload: '{"warning":{"duration":0,"mode":"stop","strobe":false}}'
        qos: 0
        retain: true
        topic: zigbee/0x000d6f0014f82b49/set
- id: "1580662281260"
  alias: "Color arming"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "arming"
  action:
    - data:
        brightness: 255
        entity_id: light.aqara_hub_fed8
        rgb_color:
          - 255
          - 255
          - 0
      service: light.turn_on
- id: "1580662281261"
  alias: "Color armed"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "armed_away"
  action:
    - data:
        entity_id: light.aqara_hub_fed8
      service: light.turn_off
- id: "1580662281262"
  alias: "Color pending"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "pending"
  action:
    - data:
        brightness: 255
        entity_id: light.aqara_hub_fed8
        rgb_color:
          - 255
          - 255
          - 0
      service: light.turn_on
- id: "1580662281263"
  alias: "Color triggered"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "triggered"
  action:
    - data:
        brightness: 255
        entity_id: light.aqara_hub_fed8
        rgb_color:
          - 255
          - 0
          - 0
      service: light.turn_on
- id: "1580662281264"
  alias: "Color resolved"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "disarmed"
  action:
    - data:
        entity_id: light.aqara_hub_fed8
      service: light.turn_off
- id: "1584462735212"
  alias: Turn on UV Flower lamp
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      for: 00:30:00
      platform: state
      to: "off"
  condition:
    - condition: state
      entity_id: switch.7edae7d6_plug
      state: "off"
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
  action:
    - data:
        entity_id: switch.7edae7d6_plug
      service: switch.turn_on
- id: "1584463271926"
  alias: Turn off UV Flower lamp
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      from: "off"
      platform: state
      to: "on"
    - entity_id: binary_sensor.0x00158d00044b1132_occupancy
      from: "off"
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: switch.7edae7d6_plug
      state: "on"
  action:
    - data:
        entity_id: switch.7edae7d6_plug
      service: switch.turn_off
- id: "1587144286634"
  alias: Purifier MAX Speed
  description: ""
  trigger:
    - above: "30"
      entity_id: sensor.fb47da6e_aqi
      for: 00:00:30
      platform: numeric_state
  condition:
    - condition: state
      entity_id: fan.fb47da6e_purifier
      state: "on"
    - condition: state
      entity_id: binary_sensor.3e565972_automation_purifier
      state: "off"
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"
  action:
    - data:
        entity_id: fan.fb47da6e_purifier
        speed: favorite
      service: fan.set_speed
    - data:
        entity_id: fan.fb47da6e_purifier
        level: 17
      service: fan.xiaomi_miio_set_favorite_level
    - data:
        payload: active
        qos: 0
        retain: true
        topic: hass/automation/purifier/3e565972
      service: mqtt.publish
- id: "1587145945339"
  alias: Purifier MIN Speed
  description: ""
  trigger:
    - below: "15"
      entity_id: sensor.fb47da6e_aqi
      for: 00:00:30
      platform: numeric_state
  condition:
    - condition: state
      entity_id: fan.fb47da6e_purifier
      state: "on"
    - condition: state
      entity_id: binary_sensor.3e565972_automation_purifier
      state: "on"
  action:
    - data:
        entity_id: fan.fb47da6e_purifier
        speed: favorite
      service: fan.set_speed
    - data:
        entity_id: fan.fb47da6e_purifier
        level: 8
      service: fan.xiaomi_miio_set_favorite_level
    - data:
        payload: inactive
        qos: 0
        retain: true
        topic: hass/automation/purifier/3e565972
      service: mqtt.publish
