- id: "1580657732450"
  alias: Turn on aqara light when motion is detected
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: light.aqara_hub_fed8
      state: "off"
    - condition: numeric_state
      entity_id: sensor.0x00158d0003f36469_illuminance
      below: 25
  action:
    - data:
        brightness: 255
        entity_id: light.aqara_hub_fed8
        rgb_color:
          - 255
          - 255
          - 255
      service: light.turn_on
- id: "1580659530371"
  alias: Turn off aqara light when motion is clear
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      for: 00:05:00
      platform: state
      to: "off"
  condition:
    - condition: state
      entity_id: light.aqara_hub_fed8
      state: "on"
  action:
    - data:
        entity_id: light.aqara_hub_fed8
      service: light.turn_off
- id: "1580657732451"
  alias: Turn on gledopto light when motion is detected
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d00044b1132_occupancy
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: light.0x00124b002113a5b2_light_cct
      state: "off"
    - condition: numeric_state
      entity_id: sensor.0x00158d00044b1132_illuminance
      below: 25
    - condition: state
      entity_id: binary_sensor.c7b6ed93_automation_light
      state: "off"
  action:
    - data:
        brightness: 30
        entity_id: light.0x00124b002113a5b2_light_cct
        kelvin: 3500
      service: light.turn_on
    - data:
        brightness: 30
        entity_id: light.0x00124b002113a5b2_light_rgb
        rgb_color:
          - 1
          - 190
          - 255
      service: light.turn_on
    - data:
        payload: active
        qos: 0
        retain: true
        topic: hass/automation/light/c7b6ed93
      service: mqtt.publish
- id: "1580659530372"
  alias: Turn off gledopto light when motion is clear
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d00044b1132_occupancy
      for: 00:05:00
      platform: state
      to: "off"
  condition:
    - condition: state
      entity_id: light.0x00124b002113a5b2_light_cct
      state: "on"
    - condition: state
      entity_id: binary_sensor.c7b6ed93_automation_light
      state: "on"
  action:
    - data:
        entity_id: light.0x00124b002113a5b2_light_cct
      service: light.turn_off
    - data:
        entity_id: light.0x00124b002113a5b2_light_rgb
      service: light.turn_off
    - data:
        payload: inactive
        qos: 0
        retain: true
        topic: hass/automation/light/c7b6ed93
      service: mqtt.publish
- id: "1580662281241"
  alias: Notify entrance motion is detected
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      from: "off"
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.aqara_hub_fed8
      state: armed_away
  action:
    - service: notify.heart_live_tg
      data:
        message: Motion detector is entrance sensor
        title: "*Motion is detected*"
- id: "1584462735212"
  alias: Turn on UV Flower lamp
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      for: 00:30:00
      platform: state
      to: "off"
  condition:
    - condition: state
      entity_id: switch.7edae7d6_plug
      state: "off"
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
  action:
    - data:
        entity_id: switch.7edae7d6_plug
      service: switch.turn_on
- id: "1584463271926"
  alias: Turn off UV Flower lamp
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      from: "off"
      platform: state
      to: "on"
    - entity_id: binary_sensor.0x00158d00044b1132_occupancy
      from: "off"
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: switch.7edae7d6_plug
      state: "on"
  action:
    - data:
        entity_id: switch.7edae7d6_plug
      service: switch.turn_off
- id: "1587144286634"
  alias: Purifier MAX Speed
  description: ""
  trigger:
    - above: "30"
      entity_id: sensor.fb47da6e_aqi
      for: 00:00:30
      platform: numeric_state
  condition:
    - condition: state
      entity_id: fan.fb47da6e_purifier
      state: "on"
    - condition: state
      entity_id: binary_sensor.3e565972_automation_purifier
      state: "off"
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"
  action:
    - data:
        entity_id: fan.fb47da6e_purifier
        speed: favorite
      service: fan.set_speed
    - data:
        entity_id: fan.fb47da6e_purifier
        level: 17
      service: fan.xiaomi_miio_set_favorite_level
    - data:
        payload: active
        qos: 0
        retain: true
        topic: hass/automation/purifier/3e565972
      service: mqtt.publish
- id: "1587145945339"
  alias: Purifier MIN Speed
  description: ""
  trigger:
    - below: "15"
      entity_id: sensor.fb47da6e_aqi
      for: 00:00:30
      platform: numeric_state
  condition:
    - condition: state
      entity_id: fan.fb47da6e_purifier
      state: "on"
    - condition: state
      entity_id: binary_sensor.3e565972_automation_purifier
      state: "on"
  action:
    - data:
        entity_id: fan.fb47da6e_purifier
        speed: favorite
      service: fan.set_speed
    - data:
        entity_id: fan.fb47da6e_purifier
        level: 8
      service: fan.xiaomi_miio_set_favorite_level
    - data:
        payload: inactive
        qos: 0
        retain: true
        topic: hass/automation/purifier/3e565972
      service: mqtt.publish
