default_config:
homekit:
  auto_start: true
  port: 51829

mobile_app:

lovelace:
  mode: yaml

discovery:
  ignore:
    - yeelight

automation: !include automations.yaml
script: !include scripts.yaml
frontend: !include frontend.yaml
notify: !include notify.yaml
scene: !include scenes.yaml
telegram_bot: !include telegram.yaml
zone: !include zone.yaml

light: !include_dir_merge_list devices/lights
sensor: !include_dir_merge_list devices/sensors

remote: !include devices/remote.yaml
fan: !include devices/fan.yaml
switch: !include devices/switch.yaml
yeelight: !include devices/yeelight.yaml
binary_sensor: !include devices/binary_sensor.yaml
device_tracker: !include devices/device_tracker.yaml
alarm_control_panel: !include devices/alarm.yaml
climate: !include devices/climate.yaml

recorder: !include services/recorder.yaml
mqtt: !include services/mqtt.yaml
influxdb: !include services/influxdb.yaml

stream:

camera:
  - platform: ffmpeg
    name: 0e8b9f4c_cctv
    input: !secret camera_0e8b9f4c_cctv_input
