- name: "create iot network"
  docker_network:
    name: "{{ docker_bridge_name }}"

- name: "run hass container"
  docker_container:
    image: "homeassistant/home-assistant:2021.12"
    name: "hass"
    restart_policy: "unless-stopped"
    recreate: true
    detach: true
    pull: true
    network_mode: "host"
    volumes:
      - "/opt/docker/hass:/config"
      - "/dev/bus/usb:/dev/bus/usb"
      - "/var/run/dbus:/var/run/dbus"
      - "/etc/timezone:/etc/timezone:ro"
