- id: "1580662281260"
  alias: "Color arming"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "arming"
  action:
    - data:
        brightness: 255
        entity_id: light.7b61e1d1_color_strip
        rgb_color:
          - 255
          - 255
          - 0
      service: light.turn_on

- id: "1580662281261"
  alias: "Color armed"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "armed_away"
  action:
    - data:
        entity_id: light.7b61e1d1_color_strip
      service: light.turn_off

- id: "1580662281262"
  alias: "Color pending"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "pending"
  action:
    - data:
        brightness: 255
        entity_id: light.7b61e1d1_color_strip
        rgb_color:
          - 255
          - 255
          - 0
      service: light.turn_on

- id: "1580662281263"
  alias: "Color triggered"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "triggered"
  action:
    - data:
        brightness: 255
        entity_id: light.7b61e1d1_color_strip
        rgb_color:
          - 255
          - 0
          - 0
      service: light.turn_on

- id: "1580662281264"
  alias: "Color resolved"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.f36e737f
      to: "disarmed"
  action:
    - data:
        entity_id: light.7b61e1d1_color_strip
      service: light.turn_off
