global:
  scrape_interval: 15s
  external_labels:
    monitor: "xeon-monitor"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "172.17.0.1:9101"
          - "192.168.10.13:9101"
          - "192.168.70.31:9101"

  - job_name: "speedtest"
    scrape_interval: 5m
    scrape_timeout: 2m
    metrics_path: /probe
    static_configs:
      - targets:
          - "speedtest:9516"
