- name: "run plex container"
  docker_container:
    image: "lscr.io/linuxserver/plex:1.32.7"
    name: "plex"
    restart_policy: "unless-stopped"
    restart: true
    detach: true
    pull: true
    network_mode: "host"
    volumes:
      - "/plex/library:/config"
      - "/plex/media:/media"
      - "/etc/timezone:/etc/timezone:ro"
    labels:
      traefik.enable: "true"
      traefik.http.routers.plex.rule: "Host(`plex.ieee5387.space`)"
      traefik.http.services.plex.loadbalancer.server.port: "32400"
    env:
      PUID: "1000"
      PGID: "1000"
      VERSION: "{{ plex_version }}"
      PLEX_CLAIM: "{{ plex_claim }}"
