- name: "copy traefik config"
  copy:
    src: "files/traefik.yaml"
    dest: "/etc/docker/traefik/"

- name: "copy traefik dynamic config"
  copy:
    src: "files/dynamic"
    dest: "/etc/docker/traefik/dynamic/"

- name: "copy traefik secure key"
  copy:
    src: "../.secrets/ca/traefik/new/live.key"
    dest: "/etc/docker/traefik/secure/"
    mode: "600"

- name: "copy traefik secure certificate"
  copy:
    src: "../.secrets/ca/traefik/new/live.crt"
    dest: "/etc/docker/traefik/secure/"
    mode: "644"
