- name: "Create iot network"
  docker_network:
    name: "{{ docker_bridge_name }}"

- name: "Run Traefik container"
  docker_container:
    image: "traefik:v2.2"
    name: "traefik"
    restart_policy: "unless-stopped"
    recreate: true
    detach: true
    pull: true
    network_mode: "{{ docker_bridge_name }}"
    volumes:
      - "/etc/docker/traefik:/etc/traefik"
    ports:
      - "8085:8080"
      - "443:443"
