- platform: mqtt
  name: 3e565972_automation_purifier
  state_topic: "hass/automation/purifier/3e565972"
  payload_on: "active"
  payload_off: "inactive"
- platform: mqtt
  name: c7b6ed93_automation_light
  device_class: connectivity
  state_topic: "hass/automation/light/c7b6ed93"
  payload_on: "active"
  payload_off: "inactive"
- platform: mqtt
  name: e2153f77_automation_light
  device_class: connectivity
  state_topic: "hass/automation/light/e2153f77"
  payload_on: "active"
  payload_off: "inactive"
- platform: mqtt
  name: 5958a8ec_automation_fan
  device_class: connectivity
  state_topic: "hass/automation/fan/5958a8ec"
  payload_on: "active"
  payload_off: "inactive"
- platform: mqtt
  name: 93ad2a47_climate_cool
  device_class: connectivity
  state_topic: "hass/script/climate/93ad2a47"
  payload_on: "cool"
  payload_off: "off"
- platform: mqtt
  name: 93ad2a47_climate_heat
  device_class: connectivity
  state_topic: "hass/script/climate/93ad2a47"
  payload_on: "heat"
  payload_off: "off"
