- platform: xiaomi_miio
  host: !secret switch_1d42d23a_plug_host
  token: !secret switch_1d42d23a_plug_token
  name: 1d42d23a_plug
  model: chuangmi.plug.m1
- platform: xiaomi_miio
  host: !secret switch_7edae7d6_plug_host
  token: !secret switch_7edae7d6_plug_token
  name: 7edae7d6_plug
  model: chuangmi.plug.m1
