all:
  hosts:
    heart.xeon:
      ansible_host: 192.168.10.12
      ansible_user: ubuntu
      ansible_dir: /home/ubuntu
      os_name: linux
      os_arch: amd64
      zigbee_pan_id: 0x1a62
      zigbee_channel: 25
      zigbee_serial_port: "/dev/ttyACM0"
      zigbee_base_topic: "zigbee"
      zigbee_client_id: "ZIGBEE_BRIDGE"
      zigbee_mqtt_server: "mqtt://mosquitto:1883"
      kios_mqtt_base_topic: "kios"
      kios_mqtt_secure: "false"
      kios_mqtt_verify: "false"
      kios_mqtt_server: "192.168.10.12"
      kios_mqtt_port: "1883"
      kios_mqtt_throttle: "1"
      kios_stream_port: "8889"
      kios_stream_quality: "100"
      kios_stream_fps: "25"
    heart.nano3:
      ansible_host: 192.168.10.13
      ansible_user: root
      ansible_dir: /root
      os_name: linux
      os_arch: arm64
      zigbee_pan_id: 0x1b64
      zigbee_channel: 11
      zigbee_serial_port: "/dev/ttyUSB0"
      zigbee_base_topic: "zigbeer"
      zigbee_client_id: "ZIGBEER_BRIDGE"
      zigbee_mqtt_server: "mqtt://192.168.10.12:1883"
