all:
  hosts:
    heart.xeon:
      ansible_host: 192.168.10.12
      ansible_user: ubuntu
      ansible_dir: /home/ubuntu
      os_name: linux
      os_arch: amd64
      zigbee_pan_id: 0x1a62
      zigbee_channel: 25
      zigbee_serial_port: "/dev/ttyACM0"
    heart.nano3:
      ansible_host: 192.168.10.13
      ansible_user: root
      ansible_dir: /root
      os_name: linux
      os_arch: arm64
      zigbee_pan_id: 0x1b62
      zigbee_channel: 11
      zigbee_serial_port: "/dev/ttyACM0"