all:
  hosts:
    heart.cloud:
      ansible_host: 51.15.198.76
      ansible_user: root
    heart.xeon:
      ansible_host: 192.168.10.12
#      ansible_host: 10.8.0.2
      ansible_user: ubuntu
      ansible_dir: /home/ubuntu