- name: Heart Docker
  hosts:
    - heart.xeon
#    - heart.nano3
  gather_facts: false
  become: true
  roles:
#    - kerberos-1
#    - prometheus
#    - hass
#     - postgres
#    - rass
#    - zigbee
#    - utorrent
    - hass
#    - mosquitto
#    - nginx
#    - filebeat
#    - traefik
