- name: "create iot network"
  docker_network:
    name: "{{ docker_bridge_name }}"

- name: "run rass container"
  docker_container:
    image: "mkerix/room-assistant"
    name: "rass"
    restart_policy: "unless-stopped"
    recreate: true
    detach: true
    pull: true
    network_mode: "host"
    volumes:
      - "/etc/docker/rass:/room-assistant/config"
      - "/dev/bus/usb:/dev/bus/usb"
      - "/var/run/dbus:/var/run/dbus"
      - "/etc/timezone:/etc/timezone:ro"
