- name: "create iot network"
  docker_network:
    name: "{{ docker_bridge_name }}"

- name: "run traefik container"
  docker_container:
    image: "traefik:v2.10.7"
    name: "traefik"
    restart_policy: "unless-stopped"
    recreate: true
    detach: true
    pull: true
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--log.level=debug"
    networks:
      - name: "{{ docker_bridge_name }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/docker/traefik/digestauth:/etc/traefik/digestauth"
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: "Host(`traefik.ieee5387.space`)"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.api.middlewares: "auth"
      traefik.http.middlewares.auth.digestauth.usersfile: "/etc/traefik/digestauth/users.passwd"
    etc_hosts:
      host.docker.internal: "172.17.0.1"
    ports:
      - "80:80"
