- id: "1580657732440"
  alias: "Turn on floor color light"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_1_single"
  action:
    - data:
        brightness: 255
        kelvin: 5000
        entity_id: light.32ebdcd1_color_bulb
      service: light.turn_on
- id: "1580657732441"
  alias: "Turn on floor color dark"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_1_double"
  action:
    - data:
        brightness: 127
        kelvin: 4000
        entity_id: light.32ebdcd1_color_bulb
      service: light.turn_on
- id: "1580657732442"
  alias: "Turn off floor color"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_1_hold"
  action:
    - data:
        entity_id: light.32ebdcd1_color_bulb
      service: light.turn_off
- id: "1580657732430"
  alias: "Turn on dev color green"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_2_single"
  action:
    - data:
        brightness: 255
        rgb_color:
          - 71
          - 255
          - 117
        entity_id: light.0xd74d40c9abfc8a14
      service: light.turn_on
- id: "1580657732431"
  alias: "Turn on dev color light"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_2_double"
  action:
    - data:
        brightness: 255
        kelvin: 4000
        entity_id: light.0xd74d40c9abfc8a14
      service: light.turn_on
- id: "1580657732432"
  alias: "Turn off dev color"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_2_hold"
  action:
    - data:
        entity_id: light.0xd74d40c9abfc8a14
      service: light.turn_off
- id: "1580657732420"
  alias: "Turn on all color"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_3_single"
  action:
    - data:
        entity_id: light.lv_color_all
      service: light.turn_on
- id: "1580657732422"
  alias: "Turn off all color"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_3_hold"
  action:
    - data:
        entity_id: light.lv_color_all
      service: light.turn_off
- id: "1580657732460"
  alias: "Turn on rainbow effect"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_4_single"
  action:
    - data:
        entity_id: light.27e18cda_light
      service: light.turn_on
    - data:
        brightness: 255
        entity_id: light.27e18cda_light
      service: light.turn_on
    - data:
        white_value: 255
        entity_id: light.27e18cda_light
      service: light.turn_on
    - data:
        effect: Rainbow
        entity_id: light.27e18cda_light
      service: light.turn_on
- id: "1580657732461"
  alias: "Turn on blinking color"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_4_double"
  action:
    - data:
        entity_id: light.27e18cda_light
      service: light.turn_on
    - data:
        brightness: 50
        entity_id: light.27e18cda_light
      service: light.turn_on
    - data:
        white_value: 50
        entity_id: light.27e18cda_light
      service: light.turn_on
    - data:
        effect: Purple blinking
        entity_id: light.27e18cda_light
      service: light.turn_on
- id: "1580657732462"
  alias: "Turn off dev color"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_4_hold"
  action:
    - data:
        entity_id: light.27e18cda_light
      service: light.turn_off
- id: "1580657732470"
  alias: "Turn on bedroom"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_6_single"
  action:
    - data:
        brightness: 255
        kelvin: 4000
        entity_id: light.br_color_all
      service: light.turn_on
- id: "1580657732471"
  alias: "Turn on bedroom"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_6_double"
  action:
    - data:
        brightness: 63
        kelvin: 3000
        entity_id: light.br_color_all
      service: light.turn_on
- id: "1580657732472"
  alias: "Turn off bedroom"
  description: ""
  trigger:
    - entity_id: sensor.0x04cf8cdf3c79818a_action
      platform: state
      to: "button_6_hold"
  action:
    - data:
        entity_id: light.br_color_all
      service: light.turn_off
