- id: "1580657732450"
  alias: Turn on aqara light when motion is detected
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      platform: state
      to: "on"
  condition:
    - condition: state
      entity_id: light.aqara_hub_fed8
      state: "off"
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.0x00158d0003f36469_illuminance
          below: 25
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
  action:
    - data:
        brightness: 255
        entity_id: light.aqara_hub_fed8
        rgb_color:
          - 255
          - 255
          - 255
      service: light.turn_on
- id: "1580659530371"
  alias: Turn off aqara light when motion is clear
  description: ""
  trigger:
    - entity_id: binary_sensor.0x00158d0003f36469_occupancy
      for: 00:05:00
      platform: state
      to: "off"
  condition:
    - condition: state
      entity_id: light.aqara_hub_fed8
      state: "on"
  action:
    - data:
        entity_id: light.aqara_hub_fed8
      service: light.turn_off
