- id: "1587144286734"
  alias: Humidifier Bedroom High
  description: High
  trigger:
    - platform: numeric_state
      entity_id: sensor.fb0dd915_humidity
      below: 35
      for: 00:05:00
  condition:
    - condition: state
      entity_id: fan.050ecc97_humidifier
      state: "on"
    - condition: template
      value_template: "{{ state_attr('fan.050ecc97_humidifier', 'no_water') is false }}"
    - condition: template
      value_template: "{{ state_attr('fan.050ecc97_humidifier', 'water_tank_detached') is false }}"
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.050ecc97_humidifier
        speed: high

- id: "1587144286735"
  alias: Humidifier Bedroom Low
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.fb0dd915_humidity
      above: 50
      for: 00:05:00
  condition:
    - condition: state
      entity_id: fan.050ecc97_humidifier
      state: "on"
    - condition: template
      value_template: "{{ state_attr('fan.050ecc97_humidifier', 'no_water') is false }}"
    - condition: template
      value_template: "{{ state_attr('fan.050ecc97_humidifier', 'water_tank_detached') is false }}"
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.050ecc97_humidifier
        speed: low

- id: "1587144286834"
  alias: Humidifier Living Room High
  description: High
  trigger:
    - platform: numeric_state
      entity_id: sensor.0e8b9f4c_humidity
      below: 35
      for: 00:05:00
  condition:
    - condition: state
      entity_id: fan.f2fac8f1_humidifier
      state: "on"
    - condition: template
      value_template: "{{ state_attr('fan.f2fac8f1_humidifier', 'no_water') is false }}"
    - condition: template
      value_template: "{{ state_attr('fan.f2fac8f1_humidifier', 'water_tank_detached') is false }}"
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.f2fac8f1_humidifier
        speed: high

- id: "1587144286835"
  alias: Humidifier Living Room Low
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.0e8b9f4c_humidity
      above: 50
      for: 00:05:00
  condition:
    - condition: state
      entity_id: fan.f2fac8f1_humidifier
      state: "on"
    - condition: template
      value_template: "{{ state_attr('fan.f2fac8f1_humidifier', 'no_water') is false }}"
    - condition: template
      value_template: "{{ state_attr('fan.f2fac8f1_humidifier', 'water_tank_detached') is false }}"
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.f2fac8f1_humidifier
        speed: low
