http:
  routers:
    traefik-router:
      rule: "Host(`router.heart`)"
      service: "traefik-router"
      tls: {}
    hass:
      rule: "Host(`hass.heart`)"
      service: "hass"
      tls: {}
    grafana:
      rule: "Host(`grafana.heart`)"
      service: "grafana"
      tls: {}
    motioneye:
      rule: "Host(`motioneye.heart`)"
      service: "motioneye"
      tls: {}
    utorrent:
      rule: "Host(`utorrent.heart`)"
      service: "utorrent"
      tls: {}
    kibana:
      rule: "Host(`kibana.heart`)"
      service: "kibana"
      tls: {}
    plex:
      rule: "Host(`plex.heart`)"
      service: "plex"
      tls: {}
