http:
  services:
    home-assistant:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:8123"
    grafana:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:3010"
    motioneye:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:8765"
    utorrent:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:8080"
    kibana:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5601"
    plex:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:32400"
