http:
  services:
    traefik-router:
      loadBalancer:
        servers:
          - url: "http://localhost:8080"
    hass:
      loadBalancer:
        servers:
          - url: "http://192.168.70.31:8123"
    grafana:
      loadBalancer:
        servers:
          - url: "http://192.168.10.12:3010"
    utorrent:
      loadBalancer:
        servers:
          - url: "http://192.168.10.12:8070"
    kibana:
      loadBalancer:
        servers:
          - url: "http://192.168.10.12:5601"
    plex:
      loadBalancer:
        servers:
          - url: "http://192.168.10.12:32400"
    zigbee:
      loadBalancer:
        servers:
          - url: "http://192.168.10.13:12000"
    shinobi:
      loadBalancer:
        servers:
          - url: "http://192.168.10.12:17000"
