api_version: 2
ssl: false
host: localhost
port: 8088
token: !secret influx_token
organization: !secret influx_organization
bucket: hass
measurement_attr: entity_id
ignore_attributes:
  - free_heap_size
  - friendly_name
  - unit_of_measurement
  - device
  - elapsed
  - last_seen
include:
  entity_globs:
    - sensor.*_battery
    - sensor.*_soil_moisture
  entities:
    - sensor.10037c21_mi_battery
    - sensor.10037c21_mi_temperature
    - sensor.10037c21_mi_humidity
    - sensor.fb0dd915_temperature
    - sensor.fb0dd915_humidity
    - sensor.fb0dd915_pressure
    - sensor.fb0dd915_resistance
    - sensor.fb0dd915_quality
    - sensor.fb0dd915_quality_accuracy
    - sensor.fb0dd915_quality_index
    - sensor.fb0dd915_co
    - sensor.fb0dd915_co2
    - sensor.fb0dd915_co2_index
    - sensor.0e8b9f4c_temperature
    - sensor.0e8b9f4c_humidity
    - sensor.0e8b9f4c_pressure
    - sensor.0e8b9f4c_resistance
    - sensor.0e8b9f4c_quality
    - sensor.0e8b9f4c_quality_accuracy
    - sensor.0e8b9f4c_quality_index
    - sensor.0e8b9f4c_co2
    - sensor.0e8b9f4c_co2_index
    - sensor.fb47da6e_aqi
    - sensor.fb47da6e_illuminance
    - sensor.0x00158d0004216ea2_temperature
    - sensor.0x00158d0004216ea2_humidity
    - sensor.0x00158d0004216ea2_pressure
    - sensor.0x00158d000410b370_temperature
    - sensor.0x00158d000410b370_humidity
    - sensor.0x00158d000410b370_pressure
    - sensor.0x04cf8cdf3c75a326_power
    - sensor.0x04cf8cdf3c75a785_power
    - sensor.0x00158d0004855eef_smoke
    - sensor.0x00158d0004855eef_smoke_density
    - sensor.0xec1bbdfffe871f0b_temperature
    - sensor.0xec1bbdfffe871f0b_humidity
