- name: "create iot network"
  docker_network:
    name: "{{ docker_bridge_name }}"

- name: "run prometheus container"
  docker_container:
    image: "prom/prometheus:v2.23.0"
    name: "prometheus"
    restart_policy: "unless-stopped"
    recreate: true
    detach: true
    pull: true
    networks:
      - name: "{{ docker_bridge_name }}"
    ports:
      - "9090:9090"
    volumes:
      - "/etc/docker/prometheus:/etc/prometheus"
