- name: "create iot network"
  docker_network:
    name: "{{ docker_bridge_name }}"

- name: "create obfs4-bridge volume"
  community.docker.docker_volume:
    name: obfs4-bridge

- name: "run obfs4-bridge container"
  docker_container:
    image: "thetorproject/obfs4-bridge:0.16"
    name: "obfs4-bridge"
    restart_policy: "unless-stopped"
    restart: true
    detach: true
    pull: true
    networks:
      - name: "{{ docker_bridge_name }}"
    ports:
      - "443:443/tcp"
    volumes:
      - "obfs4-bridge:/var/lib/tor"
    env:
      EMAIL: "vps@anonymous"
      NICKNAME: "anonymous"
      OR_PORT: "9001"
      PT_PORT: "443"
      OBFS4_ENABLE_ADDITIONAL_VARIABLES: "1"
      OBFS4V_PublishServerDescriptor: "0"
      OBFS4V_AddressDisableIPv6: "1"
