entryPoints:
  traefik:
    address: ":8080"
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  file:
    directory: "/etc/traefik/dynamic"

api:
  insecure: true

log:
  level: "debug"

#serversTransport:
#  insecureSkipVerify: true
