- name: "create iot network"
  docker_network:
    name: "{{ docker_bridge_name }}"

- name: "run speedtest prometheus container"
  docker_container:
    image: "jraviles/prometheus_speedtest"
    name: "speedtest"
    restart_policy: "unless-stopped"
    recreate: true
    detach: true
    pull: true
    networks:
      - name: "{{ docker_bridge_name }}"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "9516:9516"
