- name: "Copy mosquitto config"
  copy:
    src: "files/mosquitto.conf"
    dest: "/etc/docker/mosquitto/config/"

- name: "Copy ca certificate"
  copy:
    src: "../.secrets/ca/mosquitto/ca.crt"
    dest: "/etc/docker/mosquitto/secure/"
    mode: "644"

- name: "Copy server key"
  copy:
    src: "../.secrets/ca/mosquitto/server.key"
    dest: "/etc/docker/mosquitto/secure/"
    mode: "600"

- name: "Copy server certificate"
  copy:
    src: "../.secrets/ca/mosquitto/server.crt"
    dest: "/etc/docker/mosquitto/secure/"
    mode: "644"
