- name: "create iot network"
  docker_network:
    name: "{{ docker_bridge_name }}"


- name: "encrypt mosquitto passwd"
  docker_container:
    image: "eclipse-mosquitto:1.6.12"
    name: "mosquitto-passwd"
    auto_remove: true
    pull: true
    command: "mosquitto_passwd -U /mosquitto/config/passwd"
    networks:
      - name: "{{ docker_bridge_name }}"
    volumes:
      - "/etc/docker/mosquitto:/mosquitto"

- name: "run mosquitto container"
  docker_container:
    image: "eclipse-mosquitto:1.6.12"
    name: "mosquitto"
    restart_policy: "unless-stopped"
    recreate: true
    detach: true
    pull: true
    networks:
      - name: "{{ docker_bridge_name }}"
    volumes:
      - "/etc/docker/mosquitto:/mosquitto"
      - "mosquitto-data:/mosquitto/data"
      - "mosquitto-log:/mosquitto/log"
    ports:
      - "8883:8883"
      - "1883:1883"
