- name: "Create iot network"
  docker_network:
    name: "{{ docker_bridge_name }}"

- name: "Run Mosquitto container"
  docker_container:
    image: "eclipse-mosquitto"
    name: "mosquitto"
    restart_policy: "unless-stopped"
    recreate: true
    detach: true
    pull: true
    network_mode: "{{ docker_bridge_name }}"
    volumes:
      - "/etc/docker/mosquitto:/mosquitto"
      - "mosquitto-data:/mosquitto/data"
      - "mosquitto-log:/mosquitto/log"
    ports:
      - "8883:8883"
